version: '3.8'

services:
  # Simple nginx proxy for clean domains
  nginx:
    image: nginx:alpine
    container_name: shipnorth-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    depends_on:
      - shipnorth

  shipnorth:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: shipnorth-app
    ports:
      - "8849:8849"  # Web frontend
      - "8850:8850"  # API backend
    volumes:
      # Bind mount the entire project for development
      - .:/app
      # Persist node_modules to avoid reinstalling on every container start
      - node_modules:/app/node_modules
      - api_node_modules:/app/apps/api/node_modules
      - web_node_modules:/app/apps/web/node_modules
    environment:
      - NODE_ENV=development
      - API_PORT=8850
      - WEB_PORT=8849
      - NEXT_PUBLIC_API_URL=http://snapi.local.com
    command: npm run docker:dev
    restart: unless-stopped
    # Ensure the container has access to file system events for hot reload
    stdin_open: true
    tty: true

volumes:
  node_modules:
  api_node_modules:
  web_node_modules: