version: '3.8'

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - AWS_REGION=us-east-1
    env_file:
      - .env
    volumes:
      - ./apps/api:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - shipnorth

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    depends_on:
      - api
    networks:
      - shipnorth

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - shipnorth

networks:
  shipnorth:
    driver: bridge

volumes:
  redis-data: