services:
  shipnorth:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: shipnorth-app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - api_node_modules:/app/apps/api/node_modules
      - web_node_modules:/app/apps/web/node_modules
    env_file:
      - .env
    command: npm run docker:dev
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - default

  postgres:
    image: postgres:15-alpine
    container_name: shipnorth-postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  node_modules:
  api_node_modules:
  web_node_modules: